[package]
name = "stadiaem-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vigem = { path = "../vigem" }
hidapi = "1.3.0"
winconsole = "0.11"